"""Generate exact point-plane-interior PT distance derivatives with SymPy."""

import argparse
from pathlib import Path


def generate_header():
    try:
        import sympy as sp
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "this symbolic diagnostic requires the optional 'sympy' package"
        ) from error

    point = sp.Matrix(sp.symbols("p0:3", real=True))
    triangle = [
        sp.Matrix(sp.symbols(f"t{vertex}_0:3", real=True))
        for vertex in range(3)
    ]
    normal = (triangle[1] - triangle[0]).cross(
        triangle[2] - triangle[0]
    )
    offset = (point - triangle[0]).dot(normal)
    energy = sp.simplify(offset**2 / normal.dot(normal))
    variables = list(point)
    for vertex in triangle:
        variables.extend(vertex)
    gradient = sp.Matrix([sp.diff(energy, variable) for variable in variables])
    hessian = sp.hessian(energy, variables)

    lines = ["// Generated by derive_point_triangle_distance.py"]
    for name, expressions in (
        ("energy", [energy]),
        ("gradient", list(gradient)),
        ("hessian", list(hessian)),
    ):
        replacements, reduced = sp.cse(expressions)
        lines.append(f"// {name}")
        lines.extend(
            f"const auto {symbol} = {sp.ccode(value)};"
            for symbol, value in replacements
        )
        lines.extend(
            f"out[{index}] = {sp.ccode(value)};"
            for index, value in enumerate(reduced)
        )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        generated = generate_header()
    except RuntimeError as error:
        parser.error(str(error))
    if args.output:
        args.output.write_text(generated, encoding="utf-8")
    else:
        print(generated, end="")


if __name__ == "__main__":
    main()
