TRACKENERGY = False
CONSTANTORQUEMODEL = False
DIMENSION = 3

# lightweight MPM
BBAR = False
FBAR = False
TPIC = False
APIC = False
PARTICLESHIFTING = False
SHAPEFUNCTION = 0
INFLUENCENODE = 2
TWOPHASESINGLELAYER = False